### ISSUE TITLE
Windows Version

### ISSUE THREAD

**Issue by jb-alvarado** [jb-alvarado/ffplayout#3]
Get script, any chance you'll make another version that works in command prompt / win OS?

_Originally posted by @refriedfood in https://github.com/jb-alvarado/ffplayout/issues/2#issuecomment-441412280_

**Comment by jb-alvarado** [comment]
I think the script should run just fin on Windows! You only need a working ffmpeg binary and a buffer tool. both need to be founded from the script. You could place ffmpeg in the same folder. And using pv (from msys2 or from cygwin) with full path in your config file.

**Comment by jb-alvarado** [comment]
Can you post the error messages? Have you setup the config file right. Specially the paths to the playlists, and logfile?

**Comment by refriedfood** [comment]
I've come to the conclusion the problem is on their end. I can stream consistantly for a few hours, and then it just dies. Not sure if it's a kill packet or what. You can try it with this account: 

rtmp://stream.ssh101.com/testingthisserver
pass: testingthisserver
View: https://www.ssh101.com/live/testingthisserver

**Comment by jb-alvarado** [comment]
I have integrate a preview mode, this uses ffplay to play it on desktops. You can use this and see if is your Computer the problem or not. Take a look in the config file.
In the past I made tests on macOS and on Linux, both works more then multiple hours.

**Comment by refriedfood** [comment]
I gave up. Doesn't work. I also tried your config on ubuntu (17.10.1-server), but it doesn't play subtitles which is absolutely necessary, and the times are not in minutes and are off.

**Comment by jb-alvarado** [comment]
Sorry to hear that it not work for you. I think in general subtitles could work, but somebody have to integrate it.

**Comment by refriedfood** [comment]
Yeah. All I want to do is run a damn hls to rtmp server and out it as m3u8. I can do file by file, one at a time with: 

`ffmpeg -re -i "/home/test/misc/1.mkv" -vcodec libx264 -vprofile baseline -g 30 -b:v 1000k -s 852x480 -acodec aac -strict -2 -b:a 192k -ac 2 -vf subtitles=/home/test/misc/1.srt -f flv rtmp://localhost:1935/show/stream`

And no problems. But, for some ridiculous reason, ffmpeg doesn't allow me to make a playlist and stream it to my rtmp like ffmpeg -re -i "/home/test/misc/PLAYLISTFILE.m3u -vcodec libx264 -vprofile baseline -g 30 -b:v 1000k -s 852x480 -acodec aac -strict -2 -b:a 192k -ac 2 -f flv rtmp://localhost:1935/show/stream
I just don't get it. I've been digging for 3 days now. ffmpeg to rtmp playlist seems impossible. Even created a VPS with ubuntu - doesn't work with vlc because it can't use the experimental aac codec for audio and it buffers like crazy. And I can't externally do it with vlc to the host because it buffers like crazy. Interally with ffmpeg I have no playlist. I seem to be screwed either way. All I want is a playlist of 50 files that play fine and neither can do it, or I just don't know the magic commands...

**Comment by jb-alvarado** [comment]
By default ffmpeg can not read playlists with video files in it. The only official way is to read a text file and concat. But when every files has its own subtitle file, that this looks bad to...

That is why I started ffplayout. I think with some modifications you are able to this to.

When you more familiar with shell scripting you can probably do something like:

```bash
for i in *.mkv; do
       ffmpeg -hide_banner -nostats -i "$i" -c:v mpeg2video [proper settings] -f mpegts -
done  | mbuffer -q -c -m 20000k | ffmpeg -hide_banner -nostats -re -fflags +igndts -thread_queue_size 512 -i pipe:0 -fflags +genpts [proper codec setting] -f flv rtmp://127.0.0.1/live/stream
```
